name: Terraform-deploy
on: workflow_dispatch
jobs:
  deploy:
    env:
      TF_DIR: terraform/infra
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Preparing infrastructure
      - name: Terraform init
        run: cd ${{ env.TF_DIR }} && terraform init
      - name: Terraform plan
        run: cd ${{ env.TF_DIR }} && terraform plan
