name: Terraform-workflow
on:
  push:
    branches:
      - main
env:
  TERRAFORM_VERSION: 1.3.0
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_DIR: terraform/infra
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get code'
        uses: actions/checkout@v3
      - name: 'Setup terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: 'Show Terraform Version'
        run: terraform -v
      - name: 'Terraform init'
        run: cd ${{ env.TF_DIR }} && terraform init && env
      - name: 'Terraform plan'
        run: cd ${{ env.TF_DIR }} && terraform plan -out=plan.tfplan
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: terraform-files
          path: |
            ${{ env.TF_DIR }}/plan.tfplan
            ${{ env.TF_DIR }}/*.lock.hcl
  deploy:
    needs:
      - plan
    environment: terraform-deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Get code'
        uses: actions/checkout@v3
      - name: 'Setup terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: 'Show Terraform Version'
        run: terraform -v
      - name: 'Terraform init'
        run: cd ${{ env.TF_DIR }} && terraform init
      - name: 'Download artifacts'
        uses: actions/download-artifact@v3
        with:
          name: terraform-files
      - name: 'Terraform deploy'
        run: |
          rm ${{ env.TF_DIR }}/.terraform.lock.hcl
          cp plan.tfplan ${{ env.TF_DIR }}
          cp .terraform.lock.hcl ${{ env.TF_DIR }}
          cd ${{ env.TF_DIR }} && terraform apply plan.tfplan

