name: Terraform-plan
on:
  push:
    branches:
      - main
jobs:
  plan:
    env:
      TF_DIR: terraform/infra
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Get code'
        uses: actions/checkout@v3
      - name: Terraform init
        run: cd ${{ env.TF_DIR }} && terraform init
      - name: 'Terraform plan'
        run: cd ${{ env.TF_DIR }} && terraform plan -out=plan.tfplan
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan-file
          path: ${{ env.TF_DIR }}/plan.tfplan

  deploy:
    needs:
      - plan
    environment: terraform-deploy
    env:
      TF_DIR: terraform/infra
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Get code'
        uses: actions/checkout@v3
      - name: 'Terraform init'
        run: cd ${{ env.TF_DIR }} && terraform init
      - name: 'Download artifacts'
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan-file
      - name: 'Terraform deploy'
        run: |
          cd ${{ env.TF_DIR }}
          cd ${{ env.GITHUB_WORKSPACE }} && ls -a

